version: "3"

services:
  db:
    image: postgis/postgis:14-3.3-alpine
    container_name: postgres-test
    command: postgres -c 'max_connections=500'
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '6432:5432'
     
  redis:
    image: docker.io/bitnami/redis:7.0
    container_name: redis-test
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    